import {
  FirestoreIcon,
  MongoDBIcon,
  MySQLIcon,
  PostgreSQLIcon,
  RedisIcon,
  SQLLiteIcon,
} from "../icons/db_icons";
import {
  FileCodeIcon,
  JsIcon,
  TsIcon,
  LuaIcon,
  CIcon,
  GoIcon,
  CPPIcon,
  CSharpIcon,
  PyIcon,
  PHPIcon,
  RubyIcon,
  KotlinIcon,
  DartIcon,
  JavaIcon,
  RustIcon,
  SwiftIcon,
  RIcon,
  BashIcon,
  PowershellIcon,
  ZshIcon,
  FishIcon,
  HtmlIcon,
  XmlIcon,
  YamlIcon,
  JsonIcon,
  MarkdownIcon,
  CssIcon,
  SassIcon,
} from "../icons/lang_icons";
import {
  ElectronIcon,
  ReactNativeIcon,
  FlutterIcon,
  VueIcon,
  AngularIcon,
  SvelteIcon,
  EmberIcon,
  NextjsIcon,
  NuxtjsIcon,
  ExpressjsIcon,
  SpringIcon,
  DjangoIcon,
  LaravelIcon,
  RailsIcon,
  FlaskIcon,
  GinIcon,
  PhoenixIcon,
  DotnetIcon,
  JestIcon,
  MochaIcon,
  PyTestIcon,
  PyTorchIcon,
  TailwindIcon,
  BootstrapIcon,
  BulmaIcon,
} from "../icons/Frame_Icons";
import {
  ReactIcon,
  JQueryIcon,
  MongooseIcon,
  ReduxIcon,
  AxiosIcon,
  PrismaIcon,
  PandasIcon,
  ChartjsIcon,
  D3Icon,
  TensorFlowIcon,
  NumPyIcon,
  MdxIcon,
} from "../icons/Lib_Icons";
import { BunIcon, DenoIcon, NodejsIcon } from "../icons/Runtime_icons";
import { BabelIcon, CargoIcon, CurlIcon, DockerIcon, ESLintIcon, GitIcon, LuaRocksIcon, NeovimIcon, NpmIcon, ParcelIcon, PipIcon, PrettierIcon, RolldownIcon, RollupIcon, TmuxIcon, VimIcon, ViteIcon, VscodeIcon, WebpackIcon } from "../icons/DevTools_Icons";
import { LinuxIcon, UbuntuIcon } from "../icons/Platform_Icons";

const all_cheat_icons = {
  default: <FileCodeIcon />,
  js: <JsIcon />,
  ts: <TsIcon />,
  lua: <LuaIcon />,
  c: <CIcon />,
  cpp: <CPPIcon />,
  cs: <CSharpIcon />,
  go: <GoIcon />,
  py: <PyIcon />,
  php: <PHPIcon />,
  rb: <RubyIcon />,
  kotlin: <KotlinIcon />,
  dart: <DartIcon />,
  java: <JavaIcon />,
  rust: <RustIcon />,
  swift: <SwiftIcon />,
  r: <RIcon />,
  mysql: <MySQLIcon />,
  postgresql: <PostgreSQLIcon />,
  mongodb: <MongoDBIcon />,
  redis: <RedisIcon />,
  firestore: <FirestoreIcon />,
  sqlite: <SQLLiteIcon />,
  nodejs: <NodejsIcon />,
  deno: <DenoIcon />,
  bun: <BunIcon />,
  git: <GitIcon />,
  electron: <ElectronIcon />,
  reactnative: <ReactNativeIcon />,
  flutter: <FlutterIcon />,
  vue: <VueIcon />,
  angular: <AngularIcon />,
  svelte: <SvelteIcon />,
  ember: <EmberIcon />,
  nextjs: <NextjsIcon />,
  nuxtjs: <NuxtjsIcon />,
  expressjs: <ExpressjsIcon />,
  spring: <SpringIcon />,
  django: <DjangoIcon />,
  laravel: <LaravelIcon />,
  rails: <RailsIcon />,
  flask: <FlaskIcon />,
  gin: <GinIcon />,
  phoenix: <PhoenixIcon />,
  dotnet: <DotnetIcon />,
  jest: <JestIcon />,
  mocha: <MochaIcon />,
  pytest: <PyTestIcon />,
  pytorch: <PyTorchIcon />,
  tailwind: <TailwindIcon />,
  bootstrap: <BootstrapIcon />,
  bulma: <BulmaIcon />,
  react: <ReactIcon />,
  jquery: <JQueryIcon />,
  mongoose: <MongooseIcon />,
  redux: <ReduxIcon />,
  axios: <AxiosIcon />,
  prisma: <PrismaIcon />,
  pandas: <PandasIcon />,
  chartjs: <ChartjsIcon />,
  d3: <D3Icon />,
  tensorflow: <TensorFlowIcon />,
  numpy: <NumPyIcon />,
  mdx:<MdxIcon/>,
  bash: <BashIcon/>,
  powershell: <PowershellIcon/>,
  zsh: <ZshIcon/>,
  fish: <FishIcon/>,
  html: <HtmlIcon/>,
  xml: <XmlIcon/>,
  yaml: <YamlIcon/>,
  json: <JsonIcon/>,
  markdown: <MarkdownIcon/>,
  css: <CssIcon/>,
  sass: <SassIcon/>,
  linux: <LinuxIcon/>,
  ubuntu: <UbuntuIcon/>,
  vscode: <VscodeIcon/>,
  vim: <VimIcon/>,
  neovim: <NeovimIcon/>,
  tmux: <TmuxIcon/>,
  curl: <CurlIcon/>,
  vite: <ViteIcon/>,
  webpack: <WebpackIcon/>,
  parcel: <ParcelIcon/>,
  rollup: <RollupIcon/>,
  rolldown: <RolldownIcon/>,
  eslint: <ESLintIcon/>,
  babel: <BabelIcon/>,
  prettier: <PrettierIcon/>,
  docker: <DockerIcon/>,
  pip: <PipIcon/>,
  npm: <NpmIcon/>,
  cargo: <CargoIcon/>,
  luarocks: <LuaRocksIcon/>,
};

export default all_cheat_icons;
